import './global.css';
import '@radix-ui/themes/styles.css';
import { Providers } from '../../public/packages/src';
import { poppins } from '../../public/packages/src/fonts/font';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} font-sans`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
